updated if vm running loop

diff --git a/config/waybar/scripts/qemuhand b/config/waybar/scripts/qemuhand
--- a/config/waybar/scripts/qemuhand
+++ b/config/waybar/scripts/qemuhand
@@ -1,15 +1,52 @@
-#!/bin/sh
+#!/bin/bash
 
 PIDS=(
     'qemu-opensuse-tw.pid'
     'qemu-ubuntu-server.pid'
 )
+QEMDIR="$HOME/qemuvirt"
+found_any_running=false
+vmstmp=$(mktemp)
 
 for running in "${PIDS[@]}"
 do
-    if [ "${running}" == "$(ls $HOME/qemuvirt/runpid)" ]; then
+    if [ "${running}" == "$(ls ${QEMDIR}/runpid/)" ]; then
         vm=${running}
         check=$(echo $vm | awk '{split($0,i,"-"); print i[2]"-"i[3];}' | sed -e 's/.pid//g')
         [[ "$vm" == *$check* ]] && kitty -e bash -c "figlet "$check"; ssh $check"
+        found_any_running=true
     fi
 done
+
+if ! $found_any_running; then
+    mapfile -t exivm < <(find "$QEMDIR/virts" -mindepth 1 -maxdepth 1 -type f -printf '%f\n' | sort)
+
+    for i in "${!exivm[@]}"; do
+        echo $((i + 1)). ${exivm[i]} >> $vmstmp
+    done
+
+    kitty -e bash -c "
+    printf '%s\n\n' 'Available VMs'
+    cat ${vmstmp}
+    read -p $'\nWhich one would you like to start? [1-'${#exivm[@]}']: ' choice
+    if [[ \$choice =~ ^[0-9]+$ ]]; then
+        if (( \$choice >= 1 && \$choice <= ${#exivm[@]} )); then
+            selected_vm='${exivm[choice-1]}'
+            printf '%s %s\n' 'Starting' \$selected_vm
+            cd \$HOME/qemuvirt/virts && ./\$selected_vm
+            sleep 1
+            exit 0
+        else
+            echo 'Invalid choice. Exiting.'
+            sleep 2
+            exit 1
+        fi
+    else
+        echo 'Invalid choice. Exiting.'
+        sleep 2
+        exit 1
+    fi
+    "
+
+    rm ${vmstmp}
+fi
